version: '3.8'
services:
    sonarqube:
        environment:
            - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
            # ENABLE LDAP
            - SONAR_SECURITY_REALM=LDAP
            - LDAP_URL=ldap://10.11.12.19:389
            - LDAP_AUTHENTICATION=simple
            - LDAP_REALM=contoso.lan
            # LDAP AUTH
            - LDAP_BINDDN=administrator@contoso.lan
            - LDAP_BINDPASSWORD=**********
            # USER CONFIG
            - LDAP_USER_BASEDN=dc=contoso,dc=lan
            - LDAP_USER_REQUEST=(&(objectClass=user)(sAMAccountName={login}))
            - LDAP_USER_EMAILATTRIBUTE=cn
            - LDAP_USER_REALNAMEATTRIBUTE=cn
            # GROUP CONFIG
            - LDAP_GROUP_REQUEST=(&(objectClass=group)(member={dn}))
            - LDAP_GROUP_BASEDN=dc=contoso,dc=lan
            - LDAP_GROUP_IDATTRIBUTE=sAMAccountName
            # GENERAL SETTINGS
            - SONAR_AUTHENTICATOR_DOWNCASE=true
            - SONAR_LOG_LEVEL=DEBUG
        ports:
            - '9000:9000'
        image: 'sonarqube:latest'